# Generated by Django 5.0.8 on 2024-11-22 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilClientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('linea_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dias_pago', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('unidad', 'Unidad de Medida'), ('talla', 'Talla de Ropa')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_staff', models.CharField(blank=True, max_length=255, null=True)),
                ('medio_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito o Débito'), ('efectivo', 'Efectivo')], default='efectivo', max_length=20)),
                ('glosa', models.TextField(blank=True, null=True)),
                ('subtotal', models.IntegerField(default=0)),
                ('descuento_total', models.IntegerField(default=0)),
                ('iva_total', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaBodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_recepcion', models.DateField()),
                ('orden_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('forma_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('tbc', 'TBC')], max_length=20)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.TextField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario_accion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_accion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('giro', models.CharField(max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mayorista', models.BooleanField(default=False, verbose_name='¿Es Mayorista?')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to='app.comuna')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to='app.provincia')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='app.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='app.negocio')),
            ],
        ),
        migrations.AddField(
            model_name='almacen',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('precio_mayorista', models.IntegerField(blank=True, null=True)),
                ('descuento', models.IntegerField(blank=True, null=True)),
                ('descuento_mayorista', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('registrado_reciente', 'Registrado Reciente'), ('disponible', 'Disponible'), ('sin_stock', 'Sin Stock'), ('ingresado_manual', 'Ingresado Manual')], default='registrado_reciente', max_length=20)),
                ('tasa_ila', models.IntegerField(choices=[(0, 'No aplica'), (10, 'Bebidas analcohólicas (10%)'), (18, 'Bebidas analcohólicas con alto contenido de azúcar (18%)'), (21, 'Vinos, chichas, sidras y cervezas (20.5%)'), (32, 'Licores, piscos, whisky y destilados (31.5%)'), (53, 'Cigarros puros (52.6%)'), (60, 'Tabaco elaborado (59.7%)'), (30, 'Cigarrillos (30% + impuesto específico)')], default=0, verbose_name='Tasa del Impuesto ILA')),
                ('precio_ila_diferencia', models.IntegerField(blank=True, null=True)),
                ('precio_mayorista_ila_diferencia', models.IntegerField(blank=True, null=True)),
                ('iva_precio', models.IntegerField(default=19, verbose_name='IVA Precio (%)')),
                ('iva_precio_mayorista', models.IntegerField(default=19, verbose_name='IVA Precio Mayorista (%)')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.almacen')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.marca')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.TextField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaBodegaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.PositiveIntegerField()),
                ('precio_unitario', models.IntegerField(default=0)),
                ('entrada_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app.entradabodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='app.CarritoProducto', to='app.producto'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosDevueltos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('motivo_devolucion', models.TextField(blank=True, null=True)),
                ('entrada_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='app.entradabodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='app.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Productos Devueltos',
            },
        ),
        migrations.AddField(
            model_name='entradabodega',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='app.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='app.region'),
        ),
        migrations.CreateModel(
            name='RegistroErrores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=10)),
                ('error', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='app.negocio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='comuna',
            unique_together={('nombre', 'provincia')},
        ),
        migrations.AlterUniqueTogether(
            name='provincia',
            unique_together={('nombre', 'region')},
        ),
    ]
