# Generated by Django 5.0.8 on 2024-10-03 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.negocio'),
            preserve_default=False,
        ),
    ]
