# Generated by Django 5.0.8 on 2024-10-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_almacen_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('sin_stock', 'Sin Stock'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=20),
        ),
    ]
