# Generated by Django 5.0.8 on 2024-10-03 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('proveedor', models.CharField(max_length=255)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'verbose_name_plural': 'Devoluciones a Proveedor',
            },
        ),
    ]
