# Generated by Django 5.0.8 on 2024-10-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradabodega',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.proveedor'),
        ),
    ]
