# Generated by Django 5.0.8 on 2024-10-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_entradabodega_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradabodega',
            name='proveedor',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
            preserve_default=False,
        ),
    ]
