# Generated by Django 5.0.8 on 2024-10-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_entradabodega_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='rut_empresa',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
